### ISSUE TITLE
Unhandled Exception running repack_scrpt.cpk.ps1

### ISSUE THREAD

**Issue by nicolekun2** [Thesola10/YC_English#8]
Had no trouble extracting and extracting the menu translations and they work great in-game, When I tried to use repack_scrpt.cpk.ps1 to get the modified scrpt.cpk it gave me this error,

CPK Data Mode         : Filename
Data Alignment        : 2048
Directories info mask : False
Text Code (csv)       : UTF-8
Input  Directory      : .\work\Data\StreamingAssets\scrpt.cpk.contents
Output Filename (cpk) : .\out\contents\0100D12014FC2000\romfs\Data\StreamingAssets\scrpt.cpk
0 file(s) detected.

Building a CPK file ...

Unhandled Exception: System.OverflowException: TimeSpan overflowed because the duration is too long.
   at System.TimeSpan.Subtract(TimeSpan ts)
   at CriCpkMaker.CpkMaker.GetRemainTime()
   at CriCpkMaker.CpkMaker.GetRemainTimeString()
   at ?A0x3ea0124d.makeByCsvFile(CommandInfo cmdinf)
   at main(String[] args)
   at mainCRTStartupStrArray(String[] arguments)

I'm using Windows 10, PowerShell and Yuzu.

**Comment by Thesola10** [comment]
The `cpkmakec.exe` program shipped in this repository is unfortunately not mine, and I don't have access to the source code for it.

I'd recommend reinstalling .NET 2.0/3.0/3.5, or setting a System Compatibility value like Windows XP.

**Comment by Sakimotor** [comment]
For some reason, running CpkMakeC from the powershell script in Compatibility Mode leads to a "file not found" error.

This can be easily fixed by providing the arguments to the program manually (I had to provide the full path to both the input and the output for it to work)

**Comment by Thesola10** [comment]
@nicolekun2 I may have misread the error log you provided, have you checked that there are files in the `.\work\Data\StreamingAssets\scrpt.cpk.contents` directory? Do you have a system-wide install of Python 3 and did `inucode.py` give errors beforehand?

**Comment by nicolekun2** [comment]
I do have a full install of Python 3, and I don't think inucode.py had given me errors, But I followed the instructions that @Sakimotor had written and everything seemed to work great, The game works fine with the patch. There was nothing in the \work\Data\StreamingAssets\scrpt.cpk.contents folder.

**Comment by Thesola10** [comment]
Yeah, cpkmakec can be quite fussy, I wish there was a source-available alternative :(
